### ISSUE TITLE
Update card LankaPay

### ISSUE THREAD

**Issue by aloisdg** [d-edge/Cardidy#100]
Hello,

I would like to update LankaPay. You can get LankaPay traits on [Wikipedia](https://en.wikipedia.org/wiki/Payment_card_number#Issuer_identification_number_%28IIN%29).

This card uses Luhn check validation. You can add it by replacing its inheritance from ACard to ALuhnCard. That's all. It happens here: https://github.com/d-edge/Cardidy/blob/81cd3f6929b3f61a0656960eb3b574bf1eb07c2d/src/DEdge.Cardidy/Model/Cards.cs#L108

Of course, dont forget to edit the test cases to handle this update.

If you want to solve this issue, check this [how-to guide]( https://github.com/d-edge/Cardidy/blob/main/CONTRIBUTING.md#update-a-card).

Cheers,

**Comment by blouflashdb** [comment]
I would like to work in this.

**Comment by aloisdg** [comment]
Sure :)
