### ISSUE TITLE
Add support for RuPay

### ISSUE THREAD

**Issue by aloisdg** [d-edge/Cardidy#14]
Hello,

I would like to identify card from RuPay. You can get RuPay traits on [Wikipedia](https://en.wikipedia.org/wiki/Payment_card_number#Issuer_identification_number_%28IIN%29).

If you want to solve this issue, check this [how-to guide](https://github.com/d-edge/Cardidy/blob/main/CONTRIBUTING.md#add-a-new-card).

Cheers,

**Comment by wbalbo** [comment]
Hi, please assign this to me, I will try to solve this later today or on the weekend.

Thanks.
