### ISSUE TITLE
Add support for NPS Pridnestrovie

### ISSUE THREAD

**Issue by aloisdg** [d-edge/Cardidy#19]
Hello,

I would like to identify card from NPS Pridnestrovie. You can get NPS Pridnestrovie traits on [Wikipedia](https://en.wikipedia.org/wiki/Payment_card_number#Issuer_identification_number_%28IIN%29).

If you want to solve this issue, check this [how-to guide](https://github.com/d-edge/Cardidy/blob/main/CONTRIBUTING.md#add-a-new-card).

Cheers,

**Comment by blouflashdb** [comment]
Would like to work on this.

**Comment by ntbm** [comment]
@blouflashdb Sorry I just implemented it right now 😅

**Comment by aloisdg** [comment]
@ntbm I will let this one go but next time don't start to code an issue if someone is already involve in it. Ask first :)
