### ISSUE TITLE
Add support for Solo

### ISSUE THREAD

**Issue by aloisdg** [d-edge/Cardidy#20]
Hello,

I would like to identify card from Solo. You can get Solo traits on [Wikipedia](https://en.wikipedia.org/wiki/Payment_card_number#Issuer_identification_number_%28IIN%29).

Issuing network | IIN ranges | Active | Length |  Validation
-- | -- | -- | -- | --
Solo | 6334, 6767 | No | 16, 18, 19 | Luhn

[Solo](https://en.wikipedia.org/wiki/Solo_(debit_card)) 

If you want to solve this issue, check this [how-to guide](https://github.com/d-edge/Cardidy/blob/main/CONTRIBUTING.md#add-a-new-card).

Cheers,

**Comment by aloisdg** [comment]
@blouflashdb do you want to work on this one?

**Comment by blouflashdb** [comment]
> @blouflashdb do you want to work on this one?

The card is not active anymore. Should it still be added?

**Comment by aloisdg** [comment]
Let's go :)
