### ISSUE TITLE
Add support for Switch

### ISSUE THREAD

**Issue by aloisdg** [d-edge/Cardidy#21]
Hello,

I would like to identify card from Switch. You can get Switch traits on [Wikipedia](https://en.wikipedia.org/wiki/Payment_card_number#Issuer_identification_number_%28IIN%29).

If you want to solve this issue, check this [how-to guide](https://github.com/d-edge/Cardidy/blob/main/CONTRIBUTING.md#add-a-new-card).

Cheers,

**Comment by ntbm** [comment]
I'll implement this

**Comment by aloisdg** [comment]
Sure thank you!
