### ISSUE TITLE
Change the How to Documentation

### ISSUE THREAD

**Issue by wbalbo** [d-edge/Cardidy#30]
I noticed in the [how to](https://github.com/d-edge/Cardidy/blob/main/CONTRIBUTING.md#add-a-new-card), that is not mentioned that I need to fork the project, commit my changes in my branch and then make a PR.

Because if I just make a branch from main I will not have permission to make a PR, at least I tried and get an error.

An explication on how to contribute using a fork is here: https://www.dataschool.io/how-to-contribute-on-github/

Thanks.

**Comment by wbalbo** [comment]
I think you could put this part before the "Add new card" part.

**Comment by aloisdg** [comment]
@wbalbo good idea. Do you want to submit a PR?
