### ISSUE TITLE
Suggestion to add a result model instead of [cardtype]

### ISSUE THREAD

**Issue by hey24sheep** [d-edge/Cardidy#48]
Identify function should return a result model class (serializable) instead of an IEnumerable. It will be scalable and better.

A few suggestions, when return card types from Identify function, there are 3 scenarios

1 - Card is invalid or symbols or shady
- return should be CardType.Invalid

2 - Card is not yet supported, so not found
- return should be CardType.Unkown or CardType.NotYetSupported

3 - Wrap everything inside Identify with try - catch
- return CardType.ErrorIdentifying from catch block

To add new type
- Invalid
- ErrorIdentifying (this should be instead wrapped by another class instead)

Now, cardtype should only have card types(imo). A new model should be used for Identify result which could have 

[Serializable]
IdentifyResult.cs
```
{
"Card Number": user_inputed numbe
"Identified Card Type" : {result}
"Error Identifying" : // bool? some string error? discuss?
"IsInvalid" : // if do not want to use cardtype for error handling
}
```

this should also in future could be wrapped in a bulkIdentify function which could have another property "Count".

**Comment by hey24sheep** [comment]
@aloisdg oh, I didn't see the already discussed one. Thanks 👍🏼

**Comment by aloisdg** [comment]
@hey24sheep no problem it is a deep old one. Glad you share some of our ideas ^^
