### ISSUE TITLE
Update card Verve

### ISSUE THREAD

**Issue by aloisdg** [d-edge/Cardidy#99]
Hello,

I would like to update Verve. You can get Verve traits on [Wikipedia](https://en.wikipedia.org/wiki/Payment_card_number#Issuer_identification_number_%28IIN%29).

We mostly have to:

- add `18` to this line

https://github.com/d-edge/Cardidy/blob/81cd3f6929b3f61a0656960eb3b574bf1eb07c2d/src/DEdge.Cardidy/Model/Cards.cs#L36

- make it inherit from `ALuhnCard` instead of `ACard`
- update the testcases
- update the [contributing.md](https://github.com/d-edge/Cardidy/blob/68667d04ecc08ffb61dac81cefaa64008cf16b37/CONTRIBUTING.md#L65)

If you want to solve this issue, check this [how-to guide]( https://github.com/d-edge/Cardidy/blob/main/CONTRIBUTING.md#update-a-card).

Cheers,

**Comment by blouflashdb** [comment]
I would also like to work on this please :)

**Comment by aloisdg** [comment]
Sure go ahead :)
